name: Hola mundo prueba 2
on:
  push:
    branches: [ main ]
jobs:
  job1:
    name: Pruebas
    runs-on: windows-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest -v tests/test_persona.py