name: Hola mundo prueba 2
on:
  push:
    branches: [ main ]
jobs:
  Mi-primer-job:
    name: Mi primer job 
    runs-on: windows-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}
    steps:
    - name: Imprimir
      id: imprimir
      env:
        MI_VARIABLE: Hola mundo
      run: echo "::set-output name=respuesta::${MI_VARIABLE}"

  Mi-segundo-job:
    needs: Mi-primer-job
    name: Mi segundo job
    runs-on: windows-latest
    steps:
    - name: Imprimir
      id: imprimir
      run: echo ${{needs.Mi-primer-job.outputs.salida}}